### ISSUE TITLE
Manual install for plugin fails

### ISSUE THREAD

**Issue by akshaysgithub** [rajvimalc/date-picker-plugin#4]
Hi, When I download the hpi file, and install it, I get the following error. Any ideas what am I doing wrong?

`
uploaded2231026044830544684 | Failure     -     java.util.zip.ZipException: zip END header not found 	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1567) 	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1462) 	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1469) 	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274) 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237) 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727) 	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844) 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247) 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177) 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:348) 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:319) 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:299) 	at hudson.ClassicPluginStrategy.getShortName(ClassicPluginStrategy.java:116) Caused: java.io.IOException: Failed to load /var/lib/jenkins/plugins/uploaded2231026044830544684.jpi 	at hudson.ClassicPluginStrategy.getShortName(ClassicPluginStrategy.java:120) 	at hudson.PluginManager.dynamicLoad(PluginManager.java:891) 	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2137) Caused: java.io.IOException: Failed to dynamically deploy this plugin 	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2141) 	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1821) 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:111) 	at java.base/java.lang.Thread.run(Thread.java:834)

`

**Comment by rajvimalc** [comment]
Hi Akshay... I have not been looking into this for months. I have developed this using in Windows. Looks like you are trying to import this at non Windows machine. Can you give me some more details? Like OS with version, Jenkins version, Java version... etc.

**Comment by akaliazin** [comment]
Hi guys!
many thanks to Vimalraj for the plugin - it is very useful and it works.
I was able to check it out and build on linux and then upload the hpi to jenkins.
Why don't you add  it to the common jenkins plugins repo?

**Comment by rajvimalc** [comment]
Great it works for you. I tried adding this to plugins for GA, but they rejected my request saying my plugin is more UI oriented rather functionality.

**Comment by akaliazin** [comment]
that was a silly response 
(facepalm)

**Comment by JAPRESSLEY** [comment]
Hi,

Can you please try add to jenkins repo again or explain steps for build and manual install. I am trying to install this on Linux.

Thanks in advance

**Comment by rajvimalc** [comment]
@JAPRESSLEY Updated the README file with installation instructions.
